### ISSUE TITLE
Conseguir un promedio de 20 participantes activos en los Meetups de la comunidad Rust MX

### ISSUE THREAD

**Issue by Heeled-Jim** [mozillamexico/planes#3]
## Objetivo a alcanzar: 
Conseguir un promedio de 20 participantes activos en los Meetups de la comunidad Rust MX para el evento de Marzo 2017

## Documentos relacionados:
Wiki oficial del equipo RUST de Mozilla México: https://wiki.mozilla.org/Mexico/Rust

* Enlaces:
Mozilla Activate - RUST: https://activate.mozilla.community/es/rust-hack/
Documentación oficial de RUST: https://doc.rust-lang.org/stable/book/
Proyecto Servo en GitHub: https://github.com/servo/servo
Juega con RUST: https://play.rust-lang.org/
RUST by example: http://rustbyexample.com/
Framework Web para Rust: https://rocket.rs/
Meetup de la comunidad Rust MX: https://www.meetup.com/Rust-MX/
Introducción a RUST por Mario García: http://mariog.xyz/rust-slides/#/

## Roles:
* **R**esponsable: Mario Martínez @aio00
* **A**ccountable (quien rinde cuentas): Abiel Parra @Heeled-Jim
* **S**upporter (apoyo): Edgardo Ríos @edgardorios
                                      David Salgado @KuronekoKat 
                                      Elesban Landero @tuxlan 
                                      Rodrigo Moreno @rodmoreno
                                      Alex Fuser @alexfuser
                                      Abiel Parra @Heeled-Jim
* **C**onsulted (consultado): Yuli Reyna @yulireyji, Jorge Díaz @jdiazmx 
* **I**nformed (informado): Guillermo @deimidis
                                           Rubén @nukeador  
                                           Comunidad @mozillamexico

## Lista de items:
- [x] Escribir un post de RUST para difusión en redes sociales para el domingo 27 / Nov / 2016 (R: @aio00)
- [x] Definir logística y programación del primer evento el sábado 3 / Dic / 2016 (R: @aio00 y @yulireyji)
- [x] Diseñar los contenidos del taller del primero evento para el viernes 9 / Dic / 2016 (R: @aio00)
- [x] Ayudar a la difusión del primer evento en KMMX hasta el 10 / Dic / 2016 (R: @aio00, @yulireyji, @edgardorios, @KuronekoKat, @tuxlan, @rodmoreno, @alexfuser, @jdiazmx , @Heeled-Jim)
- [ ] Con base en los dos primeros eventos realizar ajustes de logística y contenidos para los futuros eventos para el 3 / Feb / 2017 (R: @aio00, @yulireyji, @jdiazmx, @tuxlan, @Heeled-Jim)

## Issues relacionados:

* https://github.com/mozillamexico/planes/issues/8
* https://github.com/mozillamexico/planes/issues/9
* https://github.com/mozillamexico/planes/issues/10
* https://github.com/mozillamexico/planes/issues/11
* https://github.com/mozillamexico/planes/issues/12

**Comment by tuxxy** [comment]
I am not affiliated with you or your organization in any way, please remove my tag.

Thanks.

**Comment by Heeled-Jim** [comment]
Sorry @tuxxy it will not happen again...

**Comment by mariomartinezsz** [comment]
# ¡Ya se ha resuelto!

**Hay un problema con la plataforma Meetup** en la cual se pueden registrar las personas para dar seguimiento a los eventos y confirmar o cancelar su asistencia. Esto sucede específicamente con mi cuenta de usuario y el grupo de RustMX, que ha colmado su capacidad de miembros (50) en el plan gratuito de Meetup.

Para aceptar más miembros (17 en espera en este momento) se debe contratar un plan ilimitado. He intentando contratar el plan varias veces. Desde hace tres semanas. Sin éxito.

Ya he recurrido al soporte técnico. Tienen **un problema con mi cuenta de usuario**. Es muy antigua, pero ha estado sin usar planes de pago desde 2011. En medio de eso ha pasado algo técnico que no permite mejorar la cuenta con un pago. Los intentos han sido frustrantes y se han hecho cargos a mi tarjeta por la cantidad de 1USD cada vez. La última respuesta del equipo de Meetup es: 

_"Hi Mario,_

_My name is Jake and I work closely with the tech team here at Meetup HQ. My apologies for the trouble here! I’ve filed this issue with our tech team. They’ll take a closer look, and we’ll get it fixed as soon as possible._

_Until they find a way to fix the renewal status of your account, I’m afraid you won’t be able to upgrade. If in the meantime, you’d like to let new Members in, I would suggest removing inactive Members that haven’t visited the group’s homepage in a while to make room for those new Members._

_To remove inactive members from your Meetup group:_

_Head to your group’s homepage and click Members
Select Last visited to sort your members by their most recent visit to your group homepage
Under Joined, you’ll see how long it has been since that member has visited your group (clicking Last visited a second time will reverse the order they’re listed in)
Remove a member by clicking the ‘v’ next to their name, and selecting Remove member
We recommend that you email your inactive members to warn them of this change._

_I understand this is far from ideal, but we hope to have this fixed for you soon!_

_If there’s anything else I can help with in the meantime, please feel free to let me know."_

He querido compartirles el contexto del problema en virtud del **objetivo de tener 20 participantes activos para el meetup de Marzo de 2017**. Si Meetup no fuera una plataforma recurrente para que la gente explore el ecosistema para buscar grupos afines, esto no sería tema de cuidado.

El hecho es que Meetup no me brinda un fecha definitiva para solucionar la falla.

**¿Que les parece? ¿creen que sea indispensable mejorar el grupo a ilimitado?**.

De parecerles conveniente contratar el plan ilimitado, se me ocurren dos soluciones:

- ~~Esperar que Meetup arregle el problema.~~
- ~~O sumar personas con los roles de _organizadores_ al grupo e intentar mejorar el plan por medio de sus cuentas de usuarios. Esto sería de mucha ayuda.~~
- **SOLUCIÓN: he creado una cuenta alterna y me transferí el rol de organizador del grupo. Por fin pasó mi pago para convertir el grupo a tipo ilimitado.**

Espero sus comentarios.

**Comment by Heeled-Jim** [comment]
Hola @aio00, después del tercer evento ¿podemos decir que cumplimos con nuestro objetivo? :) de igual manera propongo que abramos un issue en el nuevo repo de Rust MX para darle seguimiento a la comunidad que se está generando ¿que opinas?

**Comment by yulireyji** [comment]
Hola chicxs! 

Debido a las actividades que se han dado, se puede concluir que esta actividad ya se cumplio por lo menos en la ciudad de mexico. Pasare este tema a MozActivate para generar comunidad en otras ciudades.

Gracias!

Good Vibes!

**Comment by Heeled-Jim** [comment]
Excelente!!!, procedo a cerrar este issue :)
